apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: mysql
  type: NodePort
  ports:
    - protocol: TCP
      port: 3306          # Puerto del servicio (interno del clúster)
      targetPort: 3306    # Puerto del contenedor MySQL
      nodePort: 30306     # Puerto expuesto en los nodos (puedes elegir entre 30000-32767)
