apiVersion: v1
kind: Service
metadata:
  name: flask-adivina-service
spec:
  type: NodePort
  selector:
    app: flask-adivina
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30080  # Puedes cambiarlo si está ocupado
