name: Deploy to Private Kubernetes

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: latest

    - name: Decode and configure kubeconfig
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBECONFIG_B64 }}" | base64 -d > ~/.kube/config
        chmod 600 ~/.kube/config

    - name: Test cluster access
      run: kubectl get nodes

    - name: Deploy to Kubernetes
      run: kubectl apply -f k8s/
