name: Deploy to Private Kubernetes python app

on:
  push:
    branches:
      - master
    paths:
      - 'app.py'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: latest

    - name: Test cluster access
      run: kubectl get nodes

    - name: Deploy all Kubernetes resources
      run: kubectl apply -f k8s-python/
